#!/usr/bin/env python3
"""Regenerate compact 4-bit coverage ASCII fonts. Requires Pillow + DejaVu Sans."""
from PIL import Image, ImageDraw, ImageFont
from pathlib import Path
root=Path(__file__).resolve().parents[1]
output=['/* Generated by tools/generate-studio-font.py. DejaVu Sans; see docs/FONT-LICENSE.txt. */']
for size in (18,24,32,48):
    font=ImageFont.truetype('/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf',size)
    data=[]; offsets=[]; widths=[]
    height=size+6
    for code in range(32,127):
        width=int(font.getlength(chr(code))+1)
        im=Image.new('L',(width,height)); ImageDraw.Draw(im).text((0,0),chr(code),font=font,fill=255)
        offsets.append(len(data)); widths.append(width)
        # Row runs: length and 4-bit coverage packed into one byte (max run 16).
        for y in range(height):
            row=[(im.getpixel((x,y))+8)//17 for x in range(width)]
            x=0
            while x<width:
                n=1
                while x+n<width and n<16 and row[x+n]==row[x]: n+=1
                data.append(((n-1)<<4)|row[x]); x+=n
    output += [f'static const uint8_t font{size}_data[] = {{'+','.join(map(str,data))+'};',f'static const uint32_t font{size}_offset[] = {{'+','.join(map(str,offsets))+'};',f'static const uint8_t font{size}_width[] = {{'+','.join(map(str,widths))+'};']
(root/'main/studio_font.inc').write_text('\n'.join(output)+'\n')
